apiVersion: v1
kind: ConfigMap
metadata:
 name: nextcloud-configmap
 labels:
  app: nextcloud
data:
  NEXTCLOUD_UPDATE: "1"
  ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_HOST: "postgres-service"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1"
  NEXTCLOUD_ADMIN_USER: "my_name"
  POSTGRES_DB: "postgres"

